<?php
namespace mpr\net;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-21 at 14:20:49.
 */
class multiCurlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * multiCurl object
     *
     * @var multiCurl
     */
    protected $object;

    /**
     * callback function
     *
     * @var callable $callback
     */
    protected $callback;

    /**
     * file name where put content
     *
     * @var string
     */
    protected $test_file = '/tmp/curl.test';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->tearDown();
        $this->object = new multiCurl();
        $file = $this->test_file;
        $this->callback = function($output, $info) use ($file) { file_put_contents($file, json_encode([$output, $info])); };
        unset($file);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        if(file_exists($this->test_file)) {
            unlink($this->test_file);
        }
    }

    /**
     * @covers mpr\net\multiCurl::setCallback
     */
    public function testAll()
    {
        $curl = curl_init("http://www.ya.ru");
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        $this->object->setCallback($this->callback);
        $this->object->add($curl);
        $this->object->execute();
        $wait = time() + 3;
        while(!file_exists($this->test_file) && $wait > time()) {
            usleep(250000);
        }
        $this->assertContains("yandex", file_get_contents($this->test_file));
    }
}
