<?php
namespace mpr\net;

use \mpr\net\client;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-06 at 14:42:56.
 */
class clientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $config = [
            'base_url' => 'http://api.sdstream.ru',
            'method'   => 'get'
        ];

        $this->object = new client($config);
    }

    /**
     * @covers mpr\net\client::__call
     */
    public function test__call()
    {
        $author_params = [
            'author__external_id' => 'http://championat.com',
            'hub__id'             => 8
        ];
        $result = $this->object->author_get($author_params);
        $this->assertTrue($result['status']);
    }
}
