<?php
namespace mpr\locker;

use \mpr\locker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-19 at 17:42:11.
 */
class cacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Test driver name
     *
     * @var string
     */
    protected $driver_name = "mpr_cache_memcached";

    /**
     * Test method name
     *
     * @var string
     */
    protected $test_method = "test_method";

    /**
     * Test data
     *
     * @var string
     */
    protected $test_data = "test data";

    /**
     * Test lock time
     *
     * @var string
     */
    protected $test_lock_time = 1;

    /**
     * @var cache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \mpr\locker\cache($this->driver_name);
    }

    /**
     * @covers mpr\locker\cache::getLockKey
     */
    public function testGetLockKey()
    {
        $lock_key = $this->object->getLockKey($this->test_method);
        $this->assertContains("locked:", $lock_key);
        $this->assertContains($this->test_method, $lock_key);
        $this->assertEquals("locked:{$this->test_method}", $lock_key);
    }

    /**
     * @covers mpr\locker\cache::lock
     */
    public function testLock()
    {
        $this->assertTrue($this->object->lock($this->test_method, $this->test_lock_time));
    }

    /**
     * @covers mpr\locker\cache::unlock
     */
    public function testUnlock()
    {
        /**
         * @note always return true if locked or unlocked
         */
        $this->object->unlock($this->test_method);
    }

    /**
     * @covers mpr\locker\cache::locked
     */
    public function testLocked()
    {
        $this->testLock();
        $this->assertTrue($this->object->locked($this->test_method));
        $this->object->unlock($this->test_method);
        sleep($this->test_lock_time);
        $this->assertFalse($this->object->locked($this->test_method));

        $not_cached_method = "not_cached_method";
        $this->assertFalse($this->object->locked($not_cached_method));
    }

    /**
     * @covers mpr\locker\cache::storeLockedData
     */
    public function testStoreLockedData()
    {
        /**
         * @note always return true if locked or unlocked
         */
        $this->object->storeLockedData($this->test_method, $this->test_data, $this->test_lock_time);
    }

    /**
     * @covers mpr\locker\cache::getLockedData
     */
    public function testGetLockedData()
    {
        $this->testStoreLockedData();
        $locked_data = $this->object->getLockedData($this->test_method);
        $this->assertEquals($this->test_data, $locked_data);
    }
}
