<?php
namespace mpr;

use \mpr\cache;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-20 at 19:43:55.
 */
class cacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Base instance of object
     *
     * @var cache
     */
    protected $object;

    /**
     * Test driver name
     *
     * @var string
     */
    protected $driver_name = "memcached";

    /**
     * Base class name
     *
     * @var string
     */
    protected $class_name = "\\mpr\\cache";

    /**
     * Test key
     *
     * @var string
     */
    protected $test_key = "I'am:test_key";

    /**
     * Test value
     *
     * @var string
     */
    protected $test_value = "I'am test value";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = cache::factory($this->driver_name);
    }

    /**
     * @covers mpr\cache::factory
     */
    public function testFactory()
    {
        $this->assertInstanceOf($this->class_name, cache::factory($this->driver_name));
    }

    /**
     * @covers mpr\cache\memcached::set
     */
    public function testSet()
    {
        $this->object->set($this->test_key, $this->test_value, 10);
        $this->assertEquals($this->test_value, $this->object->get($this->test_key));
    }

    /**
     * @covers mpr\cache\memcached::exists
     * @depends testSet
     */
    public function testExists()
    {
        $this->assertTrue($this->object->exists($this->test_key));
    }

    /**
     * @covers mpr\cache\memcached::get
     * @depends testExists
     */
    public function testGet()
    {
        $this->assertEquals($this->test_value, $this->object->get($this->test_key));
    }

    /**
     * @covers mpr\cache\memcached::remove
     * @depends testGet
     */
    public function testRemove()
    {
        $this->object->remove($this->test_key);
        $this->assertFalse($this->object->exists($this->test_key));
    }

    /**
     * @covers mpr\cache\memcached::clear
     * @depends testRemove
     */
    public function testClear()
    {
        $data = [
            "key1" => "value1",
            "key2" => "value2",
            "key3" => "value3",
            "key4" => "value4",
            "key5" => "value5"
        ];

        foreach($data as $key => $value) {
            $this->object->set($key, $value, 10);
        }

        try {
            $this->object->clear();
            $result = [];
            foreach($data as $key => $value) {
                if($this->object->get($key) != null || $this->object->exists($key)) {
                    $result[$key] = $this->object->get($key);
                }
            }
            $this->assertCount(0, $result);
        } catch(\Exception $e) {
            if(strpos($e->getMessage(), 'Not implemented') !== false) {
                // =)
                $this->assertTrue(true);
            }
        }
    }
}
