<?php
namespace mpr;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-21 at 10:55:04.
 */
class configTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var config
     */
    protected $object;

    /**
     * Package name
     *
     * @var string
     */
    protected $packageName = "mpr_io_input";

    /**
     * Package class
     *
     * @var string
     */
    protected $packageClass = "\\mpr\\io\\input";

    /**
     * @covers mpr\config::getPackageName
     */
    public function testGetPackageName()
    {

        $this->assertEquals($this->packageName, config::getPackageName($this->packageClass));
    }

    /**
     * @covers mpr\config::getClassName
     */
    public function testGetClassName()
    {
        $this->assertEquals($this->packageClass, config::getClassName($this->packageName));
    }

    /**
     * @covers mpr\config::getPackageConfig
     */
    public function testGetPackageConfig()
    {
        try {
            config::getPackageConfig("some_undefined_config");
        } catch(\Exception $e) {

        }
        $this->assertInstanceOf('\Exception', $e);
    }
}
