<?php
namespace mpr;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-11 at 12:11:42.
 */
class timeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers mpr\time::setSeconds
     * @covers mpr\time::getSeconds
     */
    public function testSetTimestamp()
    {
        $timestamp = time();
        $time = new time($timestamp);
        $this->assertEquals($timestamp, $time->getSeconds());
    }

    /**
     * @covers mpr\time::getDatetime
     */
    public function testGetDatetime()
    {
        $timestamp = time();
        $time = new time($timestamp);
        $this->assertEquals(date("YmdHis", $timestamp), $time->getDatetime());
    }

    /**
     * @covers mpr\time::getDate
     */
    public function testGetDate()
    {
        $format = "Y-m-d H:i:s";
        $timestamp = time();
        $time = new time($timestamp);
        $this->assertEquals(date($format, $timestamp), $time->getDate($format));
    }


    /**
     * @covers mpr\time::getHumanReadable
     */
    public function testGetHumanReadable()
    {
        $this->assertEquals('через 1 минуту', (new time(60))->getHumanReadable(time::HUMAN_TYPE_FUTURE));
    }
}
