<?php
namespace mpr\debug;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-21 at 12:52:31.
 */
class logTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        \mpr\config::$package['mpr_debug_log']['logfile'] = stream_get_meta_data(tmpfile())['uri'];

        log::init();
    }

    /**
     * @covers mpr\debug\log::put
     */
    public function testPut()
    {
        $test_comment_string = "This is test comment string";
        $test_comment_prefix = "test_it";
        log::put($test_comment_string, $test_comment_prefix);
        $config = \mpr\config::getPackageConfig("\\mpr\\debug\\log");
        $logdata = file_get_contents($config['logfile']);
        $this->assertContains($test_comment_string, $logdata);
    }
}
