<?php
namespace mpr\net;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-21 at 14:20:49.
 */
class multiCurlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var multiCurl
     */
    protected $object;

    protected $callback;

    protected $result;

    protected $testfile = '/tmp/curl.test';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->tearDown();
        $this->object = new multiCurl();
        $file = $this->testfile;
        $this->callback = function($output, $info) use ($file) { file_put_contents($file, $output); };
        $this->result = null;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        if(file_exists($this->testfile)) {
            unlink($this->testfile);
        }
    }

    /**
     * @covers mpr\net\multiCurl::setCallback
     */
    public function testAll()
    {
        $curl = curl_init("http://www.ya.ru");
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        $this->object->setCallback($this->callback);
        $this->object->add($curl);
        $this->object->execute();
        $wait = time() + 3;
        while(!file_exists($this->testfile) && $wait > time()) {
            usleep(250000);
        }
        $this->assertContains("yandex", file_get_contents($this->testfile));
    }
}
