<?php
namespace mpr\net;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-06 at 17:57:00.
 */
class requestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var request
     */
    protected $object;

    /**
     * The string to search for in google
     *
     * @var string
     */
    protected $search_string = 'blablatest';

    /**
     * The url to test for
     *
     * @var string
     */
    protected $test_url = "http://www.google.com";

    /**
     * @covers mpr\net\request::makeRequest
     */
    public function testMakeRequest()
    {
        $this->object = new request;
        $result = $this->object->makeRequest($this->test_url, ['q' => $this->search_string], 'GET');
        $this->assertContains($this->search_string, $result);

        $this->object = new request('curl');
        $result = $this->object->makeRequest($this->test_url, ['q' => $this->search_string], 'GET');
        $this->assertContains($this->search_string, $result);

//        $this->object = new request('httprequest');
//        $result = $this->object->makeRequest($this->test_url, ['q' => $this->search_string], 'GET');
//        $this->assertContains($this->search_string, $result);
    }

    /**
     * @covers mpr\net\request::setConnectTimeout
     */
    public function testSetConnectTimeout()
    {
        $this->object = new request;
        $this->object->setConnectTimeout(10);

        $this->object = new request('curl');
        $this->object->setConnectTimeout(10);

        $this->object = new request('httprequest');
        $this->object->setConnectTimeout(10);
    }

    /**
     * @covers mpr\net\request::setTimeout
     */
    public function testSetTimeout()
    {
        $this->object = new request;
        $this->object->setTimeout(60);

        $this->object = new request('curl');
        $this->object->setTimeout(60);

        $this->object = new request('httprequest');
        $this->object->setTimeout(60);
    }
}
