<?php
namespace mpr\loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-08 at 17:24:19.
 */
class preLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var preLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new preLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
    }

    /**
     * @covers mpr\loader\preLoader::addPackage
     */
    public function testAddPackage()
    {
        $this->object->addPackage('mpr_consolekit_colors');
        $this->assertContains('\\mpr\\consolekit\\colors', $this->object->getPreloadList(), print_r($this->object->getPreloadList(), true));
    }

    /**
     * @covers mpr\loader\preLoader::addClass
     */
    public function testAddClass()
    {
        $this->object->addClass('\\mpr\\consolekit\\colors');
        $this->assertContains('\\mpr\\consolekit\\colors', $this->object->getPreloadList(), print_r($this->object->getPreloadList(), true));
    }

    /**
     * @covers mpr\loader\preLoader::load
     */
    public function testLoad()
    {
        $this->assertFalse(class_exists('\\mpr\\consolekit\\colors', false));
        $this->testAddClass();
        $this->object->load();
        $this->assertTrue(class_exists('\\mpr\\consolekit\\colors', false));
        $this->tearDown();
        $this->setUp();
        $this->testAddPackage();
        $this->object->load();
        $this->assertTrue(class_exists('\\mpr\\consolekit\\colors', false));
    }
}
