<?php
namespace mpr\helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-27 at 18:05:56.
 */
class lockerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Test method name
     *
     * @var string
     */
    protected static $test_method_name = "test_method_name";

    /**
     * @covers mpr\helper\locker::lock
     */
    public function testLock()
    {
        locker::lock(self::$test_method_name);
        $this->assertTrue(locker::locked(self::$test_method_name));
    }

    /**
     * @covers mpr\helper\locker::unlock
     * @depends testLock
     */
    public function testUnlock()
    {
        $this->testLock();
        locker::unlock(self::$test_method_name);
        $this->assertFalse(locker::locked(self::$test_method_name));
    }

    /**
     * @covers mpr\helper\locker::locked
     * @depends testUnlock
     */
    public function testLocked()
    {
        $this->assertFalse(locker::locked(self::$test_method_name));
        locker::lock(self::$test_method_name);
        $this->assertTrue(locker::locked(self::$test_method_name));
        locker::unlock(self::$test_method_name);
        $this->assertFalse(locker::locked(self::$test_method_name));
    }

    /**
     * Check is function locked
     *
     * @param string $method_name
     * @return bool
     */
    public function checkFuncLocked($method_name)
    {
        return locker::locked($method_name);
    }

    /**
     * Check is function returns false
     *
     * @param string $method_name
     * @return bool
     */
    public function checkFuncFalse($method_name)
    {
        unset($method_name);
        return false;
    }

    /**
     * @covers mpr\helper\locker::strictLocked
     */
    public function testStrictLocked()
    {
        $method_name = self::$test_method_name;
        $expire = 5;
        $this->assertFalse($this->checkFuncLocked($method_name));
        $result1 = locker::strictLocked([$this, 'checkFuncLocked'], $method_name, $method_name, false, $expire);
        $this->assertTrue($result1);
        $this->assertFalse($this->checkFuncLocked($method_name));
        $result2 = locker::strictLocked([$this, 'checkFuncLocked'], $method_name, $method_name, true, $expire);
        $this->assertFalse($this->checkFuncLocked($method_name));
        $this->assertTrue($result2);
        sleep(1);
        $result3 = locker::strictLocked([$this, 'checkFuncFalse'], $method_name, $method_name, true, $expire);
        $this->assertTrue($result3);
        sleep($expire);
        $result4 = locker::strictLocked([$this, 'checkFuncFalse'], $method_name, $method_name, true, $expire);
        $this->assertFalse($result4);
    }

    /**
     * @covers mpr\helper\locker::cachedLockedFunction
     */
    public function testCachedLockedFunction()
    {
        $method_name = self::$test_method_name;
        $expire = 5;
        $this->assertFalse($this->checkFuncLocked($method_name));
        $result2 = locker::cachedLockedFunction([$this, 'checkFuncLocked'], $method_name, $method_name, $expire);
        $this->assertFalse($this->checkFuncLocked($method_name));
        $this->assertTrue($result2);
        sleep(1);
        $result3 = locker::cachedLockedFunction([$this, 'checkFuncFalse'], $method_name, $method_name, $expire);
        $this->assertTrue($result3);
        sleep($expire);
        $result4 = locker::cachedLockedFunction([$this, 'checkFuncFalse'], $method_name, $method_name, $expire);
        $this->assertFalse($result4);
    }

    /**
     * @covers mpr\helper\locker::lockedFunction
     */
    public function testLockedFunction()
    {
        $method_name = self::$test_method_name;
        $this->assertFalse($this->checkFuncLocked($method_name));
        $result1 = locker::lockedFunction([$this, 'checkFuncLocked'], $method_name, $method_name);
        $this->assertFalse($this->checkFuncLocked($method_name));
        $this->assertTrue($result1);
    }
}
