<?php
namespace mpr\net;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-06 at 18:07:14.
 */
class httpRequestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var httpRequest
     */
    protected $object;

    /**
     * The string to search for in google
     *
     * @var string
     */
    protected $search_string = 'blablatest';

    /**
     * The url to test for
     *
     * @var string
     */
    protected $test_url = "http://www.google.com";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new httpRequest;
    }

    /**
     * @covers mpr\net\httpRequest::prepare
     */
    public function testPrepare()
    {
        $resource = $this->object->prepare($this->test_url, ['q' => $this->search_string], 'GET');
        $this->assertEquals('httpRequest', get_resource_type($resource));
    }

    /**
     * @covers mpr\net\httpRequest::execute
     */
    public function testExecute()
    {
        $this->object->prepare($this->test_url, ['q' => $this->search_string], 'GET');
        $result = $this->object->execute();
        $this->assertContains($this->search_string, $result);
    }

    /**
     * @covers mpr\net\httpRequest::setConnectTimeout
     */
    public function testSetConnectTimeout()
    {
        $this->object->setConnectTimeout(10);
    }

    /**
     * @covers mpr\net\httpRequest::setTimeout
     */
    public function testSetTimeout()
    {
        $this->object->setTimeout(60);
    }
}
