<?php
namespace mpr;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-27 at 18:05:56.
 */
class lockerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Base instance of object
     *
     * @var locker
     */
    protected $object;

    /**
     * Test driver name
     *
     * @var string
     */
    protected $driver_name = "cache_memcache";

    /**
     * Test method name
     *
     * @var string
     */
    protected $test_method_name = "test_method_name";

    /**
     * Test expire seconds
     *
     * @static
     * @var int seconds
     */
    protected static $test_expire = 2;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = locker::factory($this->driver_name);
        //$this->object = locker::factory();
    }

    /**
     * @covers mpr\helper\locker->lock
     */
    public function testLock()
    {
        $this->object->lock($this->test_method_name);
        $this->assertTrue($this->object->locked($this->test_method_name));
    }

    /**
     * @covers mpr\helper\locker->unlock
     * @depends testLock
     */
    public function testUnlock()
    {
        $this->testLock();
        $this->object->unlock($this->test_method_name);
        $this->assertFalse($this->object->locked($this->test_method_name));
    }

    /**
     * @covers mpr\helper\locker->locked
     * @depends testUnlock
     */
    public function testLocked()
    {
        $this->assertFalse($this->object->locked($this->test_method_name));
        $this->object->lock($this->test_method_name);
        $this->assertTrue($this->object->locked($this->test_method_name));
        $this->object->unlock($this->test_method_name);
        $this->assertFalse($this->object->locked($this->test_method_name));
    }

    /**
     * Check is function locked
     *
     * @param string $method_name
     * @return bool
     */
    public function checkFuncLocked($method_name)
    {
        return $this->object->locked($method_name);
    }

    /**
     * Check is function returns false
     *
     * @param string $method_name
     * @return bool
     */
    public function checkFuncFalse($method_name)
    {
        unset($method_name);
        return false;
    }

    /**
     * @covers mpr\helper\locker->strictLocked
     */
    public function testStrictLocked()
    {
        $method_name = $this->test_method_name;
        $this->assertFalse($this->checkFuncLocked($method_name));
        $result1 = $this->object->strictLocked([$this, 'checkFuncLocked'], $method_name, $method_name, false, self::$test_expire);
        $this->assertTrue($result1);
        $this->assertFalse($this->checkFuncLocked($method_name));
        $result2 = $this->object->strictLocked([$this, 'checkFuncLocked'], $method_name, $method_name, true, self::$test_expire);
        $this->assertFalse($this->checkFuncLocked($method_name));
        $this->assertTrue($result2);
        sleep(1);
        $result3 = $this->object->strictLocked([$this, 'checkFuncFalse'], $method_name, $method_name, true, self::$test_expire);
        $this->assertTrue($result3);
        sleep(self::$test_expire);
        $result4 = $this->object->strictLocked([$this, 'checkFuncFalse'], $method_name, $method_name, true, self::$test_expire);
        $this->assertFalse($result4);
    }

//    /**
//     * @covers mpr\helper\locker->cachedLockedFunction
//     */
//    public function testCachedLockedFunction()
//    {
//        $method_name = $this->test_method_name;
//        $this->assertFalse($this->checkFuncLocked($method_name));
//        $result2 = $this->object->cachedLockedFunction([$this, 'checkFuncLocked'], $method_name, $method_name, self::$test_expire);
//        $this->assertFalse($this->checkFuncLocked($method_name));
//        $this->assertTrue($result2);
//        sleep(1);
//        $result3 = $this->object->cachedLockedFunction([$this, 'checkFuncFalse'], $method_name, $method_name, self::$test_expire);
//        $this->assertTrue($result3);
//        sleep(self::$test_expire);
//        $result4 = $this->object->cachedLockedFunction([$this, 'checkFuncFalse'], $method_name, $method_name, self::$test_expire);
//        $this->assertFalse($result4);
//    }
//
//    /**
//     * @covers mpr\helper\locker->lockedFunction
//     */
//    public function testLockedFunction()
//    {
//        $method_name = $this->test_method_name;
//        $this->assertFalse($this->checkFuncLocked($method_name));
//        $result1 = $this->object->lockedFunction([$this, 'checkFuncLocked'], $method_name, $method_name);
//        $this->assertFalse($this->checkFuncLocked($method_name));
//        $this->assertTrue($result1);
//    }
}