<?php
namespace mpr\locker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-20 at 12:30:42.
 */
class phpSemaphoreTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var phpSemaphore
     */
    protected $object;

    /**
     * Test driver name
     *
     * @var string
     */
    protected $driver_name = "cache_semaphore";

    /**
     * Test memory address
     *
     * @var int
     */
    protected $test_mem_address = 1;

    /**
     * Test key
     *
     * @var int
     */
    protected $test_key = 'test_key';

    /**
     * Test value
     *
     * @var string
     */
    protected $test_data = "test data";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->object = new phpSemaphore();
    }

    /**
     * @covers mpr\locker\phpSemaphore::getLockKey
     */
    public function testGetLockKey()
    {
        $this->assertInternalType('resource', $this->object->getLockKey($this->test_key));
    }
}
